# Generated by Django 5.2.1 on 2025-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='agenda_imagens/%Y/%m/'),
        ),
    ]
